---
- name: Setup OpenStack Project
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: "{{ openstack_auth_url }}"
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3
    OS_INTERFACE: public
    OS_CACERT: "{{ cacert }}"

  tasks:
  - import_role:
      name: osp-setup-project

- name: Configure OpenStack Project
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  environment:
    OS_USERNAME: "{{ user }}"
    OS_PASSWORD: "{{ passwd }}"
    OS_AUTH_URL: "{{ openstack_auth_url }}"
    OS_PROJECT_NAME: "{{ project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3
    OS_INTERFACE: public
    OS_CACERT: "{{ cacert }}"

  tasks:
  - import_role:
      name: osp-configure-managed-project

- name: Create Router and Attach Subnet
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: "{{ openstack_auth_url }}"
    OS_PROJECT_NAME: "{{ project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3
    OS_INTERFACE: public
    OS_CACERT: "{{ cacert }}"

  tasks:
  - import_role:
      name: osp-project-add-router
