---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Deploy RHEL Instance on AWS
      amazon.aws.ec2:
        key_name: aws-key
        instance_type: t2.micro
        image: ami-07dfba995513840b5
        region: eu-central-1
        wait: yes
        wait_timeout: 500
        count: 1
        vpc_subnet_id: subnet-be9bd9c4
        assign_public_ip: yes
