---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Cleanup RHEL Instance on AWS
      amazon.aws.ec2:
        region: eu-central-1
        state: 'absent'
        instance_ids: i-02d7b512c293cb11f
