---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Iterate Instances
      amazon.aws.ec2:
        region: eu-central-1
        instance_tags:
          purpose: gobuilder
        state: 'stopped'
      register: ec2

    - name: Cleanup RHEL Instance on AWS
      amazon.aws.ec2:
        region: eu-central-1
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'

    - name: tag terminated as garbage
      amazon.aws.ec2_tag:
        region: eu-central-1
        resource: '{{ ec2.instance_ids }}'
        state: 'present'
        tags:
          purpose: garbage

