---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Cleanup RHEL Instance on AWS
      use_fact_cache: True
      amazon.aws.ec2:
        region: eu-central-1
        state: 'absent'
        instance_ids:
          - "{{ ec2_id }}"
