---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Stop Instances
      amazon.aws.ec2:
        region: eu-central-1
        instance_tags:
          purpose: gobuilder
        state: 'stopped'
      register: ec2

