---
- name: Remove instance
  hosts: "{{ instance_name }}"
  become: no
  gather_facts: no
  remote_user: "{{ ssh_user }}"
  environment:
    OS_USERNAME: "{{ openstack_user }}"
    OS_PASSWORD: "{{ openstack_passwd }}"
    OS_AUTH_URL: "{{ openstack_auth_url }}"
    OS_PROJECT_NAME: "{{ openstack_project }}"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3
    OS_INTERFACE: public
    OS_CACERT: "{{ cacert }}"

  tasks:
  - import_role:
      name: osp-delete-instance
    tags: ['delete']
