---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Deploy RHEL Instance on AWS
      amazon.aws.ec2:
        key_name: aws-key
        instance_type: t2.micro
        # RHEL 7
        # image: ami-06220be3176081cf0
        # RHEL 8
        image: ami-07dfba995513840b5
        region: eu-central-1
        wait: yes
        wait_timeout: 500
        instance_tags:
          purpose: gobuilder
        exact_count: 1
        count_tag:
          purpose: gobuilder
        vpc_subnet_id: subnet-be9bd9c4
        assign_public_ip: yes
      register: ec2

    - name: Start RHEL Instance on AWS
      amazon.aws.ec2:
        instance_ids: '{{ ec2.instance_ids }}'
        region: eu-central-1
        state: "running"
        wait: True
        vpc_subnet_id: subnet-be9bd9c4
        assign_public_ip: yes
