---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Cleanup RHEL Instance on AWS
      hosts: "Development Inventory"
      use_fact_cache=True
      amazon.aws.ec2:
        region: eu-central-1
        state: 'absent'
        instance_ids: {{ instance_id }}
